package com.example.android.cop1803;

/**
 * Created by Neuer home on 11/26/2017.
 */

import java.util.ArrayList;

public class CopData {


    public static ArrayList<CopListdata> LoadDataCopButton(String foodclass) {
        ArrayList<CopListdata> data = new ArrayList<CopListdata>();

        switch (foodclass) {

            // ******  MainCOPbtn
                case "MainCOPbtn":
                data.add(new CopListdata("Beef", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Chicken", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Game", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Goose and Gosling", "0", "0", "0", "0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Guinea Hen Fowl", "0", "0", "0", "0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lamb", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Organ Meats - Offal Meats", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Ostrich", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Pork", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Poussin/Cornish Game Hen", "0", "0", "0", "0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Squab", "0", "0", "0", "0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Turkey", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Veal", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Venison", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("*** Fish ***", "0", "0", "0", "0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cephalopods", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Flat Fish", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Miscellaneous", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Non-Bony Fish", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Poke", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Round Fish", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Shellfish", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("*** Dairy and Eggs  ***", "0", "0", "0", "0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Butter", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Cheese", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Cream", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Eggs", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Milk", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Yogurt", "0", "0", "0", "0", R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("*** Vegetables ***","","","","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Artichoke","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Asparagus","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Avocados","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Bean Sprouts","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Beans-Edible","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Beans-Inedible","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Beet","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Bell Pepper, Red","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Breadfruit","1","120","0","29",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Broccoli","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Brussel Sprouts","3","40","0","7",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Cabbage","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Carrot","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Cauliflower","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Celeriac/Celery Root","2","48","0","10",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Celery Green, Giant Pascal","2","16","0","4",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Chard Swiss, Multicolored","2","24","0","4",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Chili Peppers Fresh And Dry \n 9Listed In Order of Scoville Units","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Collard Greens","2","28","0","5",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Corn","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Cucumber","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Dandelion","3","48","1","8",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Dried Beans/Peas/Lentils/Flageolet","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Edamame","9","124","0","23",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Eggplant","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Escarole","2","24","0","4",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Fennel","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Garlic","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Kale","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Kohlrabi","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Leafy Greens","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Leek/Baby Leek","1","64","0","14",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Legume and Seed Shoots","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Lettuce","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Lotus Root","0","18","0","4",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Microgreens","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Mushrooms","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("New Mexican 6-4 Heritage","","1786","","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Okra Red/Green","2","36","0","8",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Onion","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Oyster Plant","0","18","0","4",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Parsnip","0","18","0","4",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Peas-Edible","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Peas-Inedible","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Radicchio","0","6","0","2",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Radishes","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Roots and Tubers","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Salsify Black/White","0","18","0","4",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Sea Vegetables","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Shallot","1","64","0","14",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Shoots and Stems","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Sorrel","2","24","0","4",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Spinach","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Summer Squash","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Sweet Potatoes","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Tomatillo","0","44","0","8",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Tomato","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Truffles","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Turnip","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Water Chestnut","0","18","0","4",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Winter Squash","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));

                    data.add(new CopListdata("*** Fruits ***","0","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Apples","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Apricots","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Banana","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Berries","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Cherimoya","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Cherries","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Currants","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Dates","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Dragon Fruit","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Feijoa","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Figs","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Grapefruit","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Grapes","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Guava","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Kiwi","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Kumquat","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Lemons","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Limes","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Lychee","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Mango","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Mangostene","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Medlar","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Melons","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Minneola","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Murcott","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Nectarines","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Olives","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Oranges","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Papayas","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Passion Fruit","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Peaches","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Pears","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Persimmon","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Physallis/Cape Gooseberry","1","52","0","12",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Pineapple","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Plums","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Pomegranate","1","108","0","25",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Pomelo","","0","0","",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Prickly Pear","","0","0","0",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Quince","0","64","0","14",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Rhubarb","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                    data.add(new CopListdata("Sapodilla/Mexican Pear","1","64","0","16",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Star Fruit/Carambola","1","41","0","9",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Tamarillo/New Zealand","3","42","1","5",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Tangerine/Mandarin","1","48","0","11",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Ugly/Spanish Citrus","1","40","0","9",R.drawable.mic_done_black_24dp));
                    data.add(new CopListdata("Watermelon","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));



                data.add(new CopListdata("*** Nuts and Seeds  ***", "0", "0", "0", "0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Almonds","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Brazil Nuts","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Candlenuts","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cashews","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chestnuts","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chocolate","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Coconuts","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Gingko Nuts","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Hazelnut","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Linseed","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lotus Nuts","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lupin Seeds","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Macadamias","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Peanuts","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pecans","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pine Nuts","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pistachios","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Poppy Seeds","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pumpkin Seeds","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sesame Seeds","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sunflower Seeds","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tiger Nuts","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Walnuts","","","","",R.drawable.mic_done_black_24dp));
                break;
            // button btnx21 Breadings Crusts coatings Wraps
            case "btnx21":
                data.add(new CopListdata("Batters","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Bean/Legume Pastes","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Bread Crumbs","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Chopped Nuts","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Crushed Root Chip Crumbs","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Dried Fruit","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Dried Vegetables","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Edible Flowers","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Flour","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Fruit Paste","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Grain and Starch Flours","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Grains and Starches","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Mushroom Crumbs","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Mushroom Flours","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Nut Flours","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Other","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Potato Crumbs","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Seeds","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Spices","","","","", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Sugar","","","","", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Tortilla Crumbs","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));

                data.add(new CopListdata("*** Wraps ***","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cabbage Leaves","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Corn Tortillas","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Dried Fruit Leathers","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Dried Vegetable Sheets","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Edible Bowls","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Flour Tortillas","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Grape Leaves","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Indian Fry Bread/Navajo Taco","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lettuce Leaves","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Nori or Dried Seaweed Paper","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pastry Sheets","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Pastry Dough","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Phyllo Dough","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Potato Sheets","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Puff Pastry Dough","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rice Paper/Spreing Roll Wrappers","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Won Ton Wrapper","","","","",R.drawable.mic_done_black_24dp));
                break;
            // button btnx22 Manipulation
           case "btnx22":
                data.add(new CopListdata("Batonnet","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bias","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Blanching","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Blending","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Brunoise","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Channel Cut","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chiffonade","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chopping","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cutting","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Diagonal Bias","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dice","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Emulsifying","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fanning","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Filet","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fine Julienne","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fluting","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Folding","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Grinding","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Julienne","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Kabob","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Kneading","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mashing","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Medallions","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mince","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Minced","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Parisienne","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Paysanne","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pounding","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pulverizing","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Puree","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rolling","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rondelle","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Skewer","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Slicing","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Suprémes","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tenderizing","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tossing","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tourne′","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Whipping","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Zesting","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                break;
            // button btnx23 Dry Rubs and stuffing
            case "btnx23":
                data.add(new CopListdata("**** Dry Rubs ***","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Asian \n 9Ginger Root, Garlic, Crushed Red Pepper, Five Spice Powder, Coriander","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Aztec \n 9Cocoa Powder, Cumin, Chili Powder, Dehydrated Onion, Garlic, Cayenne Pepper, Salt","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("BBQ \n 9Paprika, Chili Powder, Salt, Black Pepper, Sugar, MSG, Cayenne Pepper, Celery Seed","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cajun \n 9Cayenne Pepper, Black Pepper, White Pepper, Jalapeno Pepper, Filé Powder, Salt, Sugar, Paprika, Chili Powder, Brown Sugar, Garlic, Dehydrated Onion, Celery Seed","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Creole \n 9Cayenne Pepper, Jalapeno Pepper, Filé Powder, Salt, Brown Sugar, Dehydrated Onion, Garlic, Celery Seed, Black Pepper, Fennel Seed","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Creole-alt \n 9Thyme, Paprika, Black Pepper, Garlic, Onion, Cayenne, White Pepper, Salt","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dried Fruit Rub \n 9Dried Cherries, Applies, Cranberries, Sugar, Salt","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dried Vegetable Rub \n 9Sun Dried Tomatoes, Garlic, Onion, Carrot, Celery, Mushrooms, Salt, Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fab Four \n 9Salt, Pepper, MSG, Sugar","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Garlic \n 9Granulated Garlic, Salt, Pepper, MSG, Sugar","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Herb \n 9Basil, Parsley, Oregano, Tarragon, Salt, Black Pepper, Parmesan, Rosemary, Sugar","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Jamaican Jerk \n 9All Spice, Cinnamon, Nutmeg, Chives, Thyme, Dehydrated Onion, Salt, Black Pepper, Cayenne Pepper, Brown Sugar, Paprika, Cloves, Parsley","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mesquite \n 9Paprika, Mesquite Seasoning, Black Pepper, Salt, Brown Sugar, Garlic, Cumin Seed","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mustard \n 9Mustard Powder, Sugar, Salt, Coriander, Nutmeg, Dill, Turmeric","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Peppercorn \n 9Pink Peppercorn, Green, White, Black and Red, Salt, Sugar, Thyme, Sage","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rock Crystals \n 9Dehydrated Sweet and, or Savory Stocks that Yield Crystals after Dehydration","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Salt","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Salt and Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Spicy Mustard \n 9Mustard Powder, Cayenne, Black Pepper, Chili Powder, Alum, Cracked Mustard Seed, Salt","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Spicy Rub \n 9Chili Powder, Cumin, Garlic, Oregano, Cayenne","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("West Indies \n 9Curry, Turmeric, Cardamom, Nutmeg, Cinnamon, Cumin, Salt, Black Pepper, White Pepper, Cayenne Pepper, Coriander, Ginger, Achiote","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Wild Mushroom Rub \n 9Shiitake, Enoki, Moral, Chanterelles and Button Flours, Salt and Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("*** Stuffings ***","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Berry Stuffing \n 9Bread Cubes, Strawberries, Blackberries, Gooseberries, Raspberries, Eggs, Cream, Salt, Pepper, Sugar","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Breads \n 9Brioche, Croissant, Multigrain, Baguette","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Corn Bread Stuffing \n 9Corn Bread, Butter, Onions, Carrots, Celery, Eggs, Garlic, Stock, Salt, Pepper, Sugar, Hot Sauce, Thyme, Sage, Parsley","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dried Flowers","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dried Fruits","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dried Vegetables","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fresh Flowers","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fresh Fruits","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fresh Vegetables","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mousselines \n 9Caviar, King Salmon, Oyster","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mousses \n 9Salmon, Shellfish, Pork Fillet","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mushroom Stuffing \n 9Mushroom Duxelle, White Wine, Bread Crumbs, Eggs, Stock, Salt, Pepper, Sugar, Thyme, Sage, Parsley","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Oyster Stuffing \n 9Smoked Oysters, Sashimi Tuna, Bread Cubes, Oyster Sauce, Soy Sauce, Rice Wine, Eggs, Red Chili Paste, Ginger","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sweet Breads \n 9Pumpkin, Banana, Blueberry","0","0","0","0",R.drawable.mic_done_black_24dp));
                break;
            // button btnx24 Herb and spice pastes
            case "btnx24":
                data.add(new CopListdata("*** Spice Pastes *** ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Achiote/Annatto Seed Paste  \n 9Annatto Seed Paste, Olive Oil, Cumin, Chili Powder, Cayenne Pepper, Salt, Sugar","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bases ","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Basil Pesto  \n 9Olive Oil, Basil, Garlic, Parmesan, Pine Nuts, Salt, Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("BBQ  \n 9Tomato Catsup, Red Wine Vinegar, Brown Sugar, Paprika, Chili Powder, Cumin, Black Pepper, Hot Sauce, Liquid Smoke, Salt, Worcestershire Sauce","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cilantro Pesto  \n 9Cilantro, Toasted Pecans, Garlic, Walnut Oil, Sesame Oil, Salt, Pepper, and Asiago","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Green Curry Paste  \n 9Green Chilies, Purple Shallots, Garlic, Cilantro, Lemon Grass, Galangal, Coriander, Cumin, Peppercorns, Turmeric, Shrimp Paste and Oil","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Gremolata  \n 9Parsley, Lemon Peel, Black Pepper and Garlic","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Herb and Oil  \n 9Basil, Rosemary, Oregano, Chives, Olive Oil, Walnut Oil, Salt, Pepper, Cayenne Pepper, Garlic","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Htipiti  \n 9Feta Cheese and Oregano Paste","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Korean Soybean Pastes Hot and Sweet  \n 9Fermented Pulverized Soy Beans, Sugar, Salt, Monosodium Glutamate, Red Chile, Soy Sauce","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Massaman Curry Paste  \n 9Chilies, Oil, Onion, Garlic, Shrimp Paste, Lemon Grass, Galangal, Coriander, Cumin, Fennel, Cinnamon, Cardamom, Nutmeg, and Cloves named after India’s Muslims","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Melitzanosalata  \n 9Puree of Eggplant, Garlic, Lemon and Olive Oil","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Red Curry Paste  \n 9Red Chilies, Purple Shallots, Garlic, Lemon Grass, Galangal, Kaffir Lime Rind and Leaves Oil, Shrimp Pasted, Coriander, Seeds, Cumin, Peppercorns, Paprika, and Turmeric","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sage Pesto  \n 9Sage, Toasted Walnuts, Walnut Oil, Garlic, Olive Oil, Red Wine, Salt, Pepper and Romano Cheese","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Savory Paste  \n 9Worcestershire Sauce, Salt, Pepper, Paprika, Oyster Sauce, Chili Powder, Sugar, Thyme, Dried Onion, Garlic, Cayenne Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Shichimi  \n 9Japanese Chili Spice Blend","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sweet Paste  \n 9Honey, Olive Oil, Basil, Cumin, Salt, Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tandoori  \n 9Annatto Paste, Yogurt, Chili Powder, Cayenne, Paprika, Garlic, Salt, Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Taramasalata  \n 9Fish Roe Spread","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tzatziki  \n 9Greek Sauce Puree of Cucumber, Yogurt, Garlic and Dill","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Yellow Curry Paste  \n 9Chilies, Coriander Seeds, Caraway Seeds, Cinnamon, Cloves, Red Onion, Garlic, Lemon Grass, Salt, Curry and Dry Mustard","0","0","0","0",R.drawable.mic_done_black_24dp));

                data.add(new CopListdata("*** Herbs *** ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Agustache/Korean Mint/Anise Hyssop","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Angelica","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Basil","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Bay Leaves","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bergamot","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Catnip","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Celery","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chervil","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chives","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cilantro","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cilantro/Coriander","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cilantro/Shado Beni","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Citronella","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Claytonia/Purslane","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Coriander","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Curry Leaves","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dill","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fennel","","0","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Fenugreek","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Garlic Chives","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Geranium","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Horseradish","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Houttuynia Asian Cilantro","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Hyssop","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Kaffir Lime Leaves","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Ku Chai Chinese Chives","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lavender","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lemon Grass","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lemon Thyme","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lemon Verbena","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lovage","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Marigold","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Marjoram","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Micromeria","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mint","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Mugwort","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Myrtle","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Oregano","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Pandan/Screwpine/South Pacific Grass","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Parsley","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Peppermint","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Perilla/Chinese Mint-Basil","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rice Paddy Herb","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rosemary","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sage","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Salad Burnet","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sassafras","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sassafrass Leaf File Powder","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Savory","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Sorrel","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Spearmint","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sweet Cicely","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
                break;
            // button btnx25 Marinades and Brines    ***missing some of other marinades
            case "btnx25":
                data.add(new CopListdata("*** Broths ***","0","","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("White Wine Broth ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chicken Broth ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Beef Broth ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fish Broth ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Red Wine Broth ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Saffron Broth ","0","0","0","0",R.drawable.mic_done_black_24dp));

                data.add(new CopListdata(" *** Salsas ***","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Berry Kiwi Salsa  \n 9Kiwi Puree, Strawberries, Black Berries, Blueberries, Raspberries, Parsley, Scallion,","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Creole Salsa \n 9Tomato Salsa, Celery, Onion, Green Pepper, Cilantro Hot Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cucumber Salsa ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Green Chile Salsa ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mango Salsa ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Onion Salsa ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pineapple Salsa  \n 9Pineapple, Mango, Red Onion, Garlic, Lime Juice, Sugar, Salt, Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomatillo Salsa ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomato Salsa ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tropical Fruit Salsa  \n 9Guava, Mango, Papaya, Passion, Red Pepper Puree, Scallions, Olive Oil, Cilantro, Lime","0","0","0","0",R.drawable.mic_done_black_24dp));


                data.add(new CopListdata("*** Other Marinades ***","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Almond ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Asian  \n 9Fish Sauce Soy Sauce, Oyster Sauce, Teriyaki, Ginger, Garlic, Leek, Rice","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Banana Sauce  \n 9Puree of Bananas, Red Chilies, Corn Syrup, Vinegar, Salt and Black Peppe","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Beer ","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Black Bean  \n 9Black Beans, Corn, Red Onion, Garlic, Tomatoes, Bacon, Cayenne, Black Pe","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Canola ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Caribbean  \n 9Papaya, Mango, Passion Fruit Juices, Chives, Cayenne, Allspice, Cinnamon","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Coconut ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Four Onion  \n 9Olive Oil, Red Onions, Yellow Onions, Scallions, Leeks, Honey Dijon Dres","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Four Onion Marmalade  \n 9Olive Oil, Red Onion, Yellow Onion, Scallions, Leeks, Honey, Dijon Musta","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fruit Infused ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Golden Gate  \n 9Mayonnaise, Country Mustard, Chives, Orange Rind, Rosemary, Red Wine, Bl","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Grape Seed ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Herb  \n 9Olive Oil, Red Wine Vinegar, Balsamic Vinegar, Basil, Oregano, Fennel Se","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Herb Infused ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Hickory Smoke  \n 9Oil, Vinegar, Smoke Flavor, Salt, Pepper, Brown Sugar, Celery Seed, Garl","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Honey Mustard  \n 9Honey, Dijon Mustard, Nutmeg, Curry, Mayonnaise","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Italian  \n 9Olive Oil, Oregano, Basil, Red Wine Vinegar, Salt, Black Pepper, Red Pep","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lard ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lemon Garlic  \n 9Olive Oil, Lemon Juice Oregano, Garlic, Cumin, Black Pepper, Salt","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Oils and Infused Oils ","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Palm Kernel ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Peanut ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pesto Cream Dressing  \n 9Mayonnaise, Minced Garlic, Parsley Basil, Parmesan, Buttermilk, Cracked","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rape Seed ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Red Pepper  \n 9Roasted Red Pepper Puree, Olive Oil, Red Onion Honey, Salt, Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Red Pepper, Garlic  \n 9Mayonnaise, Roasted Red Pepper Puree, Lemon Juice, Minced Garlic, Cayenn","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Red Wine  \n 9Red Wine, Red Wine Vinegar, Dijon Mustard, Sugar, Salt, Pepper","","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Safflower ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sesame ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Seviche  \n 9Lemon Juice, Lime Juice, White Wine, Salt, Pepper, Sugar","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Smoky White Bean  \n 9Cooked White Beans, Red Onion, Lemon Vinaigrette, Bacon Bits, Parsley","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Soy  \n 9Soy Sauce, Cayenne, Sesame Oil, Ginger, Garlic, Leek","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sunflower ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sweet Chile  \n 9Corn Syrup, Pineapple Juice, Raspberry Vinegar, Crushed Red Pepper, Onio","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tallow ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Teriyaki  \n 9Soy Sauce, Honey, Ginger, Garlic","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tex-Mex  \n 9Chili Oil, Ketchup, Red Wine Vinegar, Cilantro, Crushed Red Pepper, Blac","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Vegetable ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Vegetable Infused ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Walnut ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Wine  \n 9White Wine, Red Wine, Oyster Sauce, Worcestershire, Hot Sauce, Sugar","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));

                data.add(new CopListdata("*** Sauces ***","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Apricot and Ginger Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Asparagus and Cheddar Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Béchamel/White Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bitter Sweet Chocolate Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Caramel Scotch Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Demi-Glace Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Espagnole/Brown Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Hollandaise Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sorrel Mushroom Cream Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Strawberry Rhubarb Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Three Mushroom Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomato Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Veloute Sauce ","0","0","0","0",R.drawable.mic_done_black_24dp));

                data.add(new CopListdata("*** Brines ***","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Exotic Brine  \n 9Himalayan Salt, Filtered Water, Vermont Maple Syrup","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("French Brine  \n 9Fleur de Sel, Avian Water, Herb des Provence, Alpine Honey","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Polynesian Brine  \n 9Ginger, Soy Sauce, Cane Sugar, Fijian Spring Water, Black Kona Salt","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("South of the Border Brine  \n 9Agave Syrup, Poblano Chili Puree, Cerveza, Sea Salt","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Thai Brine  \n 9Lemongrass Water, Fish Sauce, Lime Juice, Rock Sugar, Ginger, Garlic}","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Traditional Brine  \n 9Water, Salt, and possibly Sugar","0","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Vegetarian Brine  \n 9Vegetable Juice/V8, Kosher Salt, Fruit Juice, Honey, Soy Sauce","0","0","0","0",R.drawable.mic_done_black_24dp));
                break;
            // button btn26 Spices and Spice Crusts
            case "btnx26":
            data.add(new CopListdata("*** Spices ***","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Akudjua/Australian Bush Tomato","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Allspice","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Amchoor/Indian Mango Evergreen Fruit","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Anise","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Annatto","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Aromatic Leaves","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Asafetida/Middle Eastern Fennel","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Barberry","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Capers","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Caraway","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Cardamom","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Cassia","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Cayenne","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Celery Seed","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Chiles","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Chili Powder","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Cinnamon","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Citrus","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Cloves","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Coriander","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Coriander Seeds","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Cubeb/Java Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Cumin","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Curry Leaves","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Dill Seeds","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Fennel Seeds","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Fenugreek","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Galangal","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Ginger","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Grains of Paradise/Guinea Pepper/Melegueta/Alligator Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Horseradish","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Indonesian Kencur","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Juniper","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Kaffir Lime","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Kokam/Indian Evergreen Fruit","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Lemon Grass","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Lemon Myrtle","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Licorice","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Mace","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Mahlab/Middle East Sour Cherry Stones","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Mastic/Greek Evergreen Resin","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Middle East Za’atar","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Mountain Pepper/Australian Black Pepper","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Mustard","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Nigella","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Nutmeg","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Paprika Spanish, Hungarian","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Pepper","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Poppy","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Rose","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Safflower","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Saffron","0","0","0","0",R.drawable.mic_done_black_24dp));
            data.add(new CopListdata("Salt","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Star Anise","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Sumac","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Tamarind","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Turmeric","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Vanilla","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Wattle/Acacia/Australian","0","0","0","0",R.drawable.ic_keyboard_arrow_right_black_24dp));
            data.add(new CopListdata("Zeodary","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
            break;
            // button btnx31 Cooking Techniques
            case "btnx31":
                data.add(new CopListdata("Baked","0","0","0","0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Beurre Manie","0","0","0","0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Boiled","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Braised","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Caramelize","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Carbonyl Amine Browning (Protein Browning)","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cold Smoked","","","","", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Deep Fried","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dry Saute","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Emulsification","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("En Papillote","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fricasseed","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Microwaved","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pan Fried","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pan Seared","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pan Smoked","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pan Stewed","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pan Toast","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Plank Broiled","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Plank Smoked","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Poached ","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Roasted","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Salt Block Roasted","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Saute","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Shallow Poacched","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Simmer","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Slurry","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Smoke Roasted","","","","", R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Sous Vide","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Steamed","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Stewed","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Suspension","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sweat","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Toasting","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Water Bath Baking","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Wok Fry","","","","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Wood Plank Roasted","","","","", R.drawable.mic_done_black_24dp));
                break;
            // button btnx41 Salads Relishes
            case "btnx41":
                data.add(new CopListdata("*** Salads  ***", "0", "0", "0", "0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Asian Pear","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Blood Orange Mozzarella","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bread and Fruit","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cabbage/Cole Slaw","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cesar","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Champagne Baby Green","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chicken Mango","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chickpea","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Creole Green Bean","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dilled Egg","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Egg","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fruit","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Gelatin and Whipped Cream","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Gelatin/Aspic","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Grain","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Greek Cucumber","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Kim Chee","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Leafy Greens","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Meat","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Meat/Protein","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Olive","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pasta","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Potatoes","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Prosciutto Melon","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Seared Tuna","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Southwest Cobb","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Spicy Carrot","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Spinach","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Squash Orzo","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Three Bean","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomato","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomato Mint","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomato-Peach","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tuna","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Vegetables","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Watercress Fruit","0","0","0","", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("*** Relishes  ***", "0", "0", "0", "0", R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("  Baba Ghanoush","0","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("  Jardiniere","0","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("  Pesto","0","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("  Pickle","0","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("  Salsa","0","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("  Tapenade","0","","","",R.drawable.mic_done_black_24dp));
                break;
            // button btnx42 Starches and Grains
            case "btnx42":
                data.add(new CopListdata("*** Starches Grains ***","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Arrowroot","0","228","0","57",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Asian Style Noodles","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Bao Buns","0","160","2","8",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Barley Pot, Pearl","0","208","0","42",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bean Products","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Beans","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Bran","0","125","2","37",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bread","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Buckwheat","0","208","2","26",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bulgar","0","210","1","40",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Buns","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Corn","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Corn Bread","0","188","6","29",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cornstarch","0","244","0","58",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Couscous","0","200","1","41",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Farina","0","208","2","26",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("File’","0","192","5","41",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Flatbread","0","192","5","41",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Flour","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Garden Peas","0","210","0.5","19",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Germ","0","207","5","28",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lentils","0","210","0.5","19",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Matzo Ball","0","96","3","12",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Millet","0","228","2","44",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Modified Food Starch","0","0","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Oat Bran","0","154","4","42",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Oatmeal","0","204","4","38",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Oats","0","204","4","38",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pasta","7","200","1","41",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Potatoes","0","58.1","0.1","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Quinoa","0","222","3.5","39",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rice","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Rice Paper","0","228","0","50",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rye","0","202","1.5","42",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Semolina","0","200","1","41",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sorghum","0","202","2","44",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tapioca","0","2226","0","54",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Wheat Whole Cracked","0","208","2","26",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Yams/Kumara","0","57","0","13",R.drawable.mic_done_black_24dp));
                break;
            // button btnx43 "Garnishes"  -  Garnishes
            case "btnx43":
                data.add(new CopListdata("Brunoise","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Capers","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cheese","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Chiffonade","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cornichon","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Croquettes","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Croutes","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Croutons","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Duxelles","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fried Starch Skins/Won Ton Skins/Wraps","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fritters","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fruit Coulis","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Fruit Oil Emulsion","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Gelatin/Aspic","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Gremolata","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Herb Oil Emulsion","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Herbs","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Julienne","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Matiganon","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mirepoix","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pasta","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Pickles","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pico de Gallo","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Potatoes","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Profiterolles","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Quenelles","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Royale","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Salpicon","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sauces","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Threaded Eggs","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Tuilles","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Vegetable Coulis","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Vegetable Oil Emulsion","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                break;
            // button btnx44 "Sauces Salsa"  -  Sauces/Salsas
            case "btnx44":
                data.add(new CopListdata("*** Sauces ***","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Alfredo","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Andalouse","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Asian","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Au Po′ivre","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Aurora Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Barbecue","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Basil","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Béchamel","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Beer Reduction","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Beer","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Bercy Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Beurre Blanc","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Beurre Rouge","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bolognese","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Bonito Broth","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chimichurri","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chocolate","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Classic Tomate/Tomato","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Cream Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Demi Glace","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Espagnole","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Fish Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fonds","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Gastrique","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Gravy","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Harissa","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Herb","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Herb Seafood Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Hollandaise","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Hot Sauce","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Hungarian Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Italian","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Jus Lié","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Kale","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Ketchup/Catsup/Tomato Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Liquor Reduction","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mayonnaise","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Mignonette","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Miso Broth","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mushroom Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mustard","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Normandy Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Oyster Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Peanut","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Peanut Butter","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pesto","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Poulette Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rémoulade","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rouille","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Seafood Fumet","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Shrimp Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Soy Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Spinach","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Supréme","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Teriyaki","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomato","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Velouté","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Vinegar Reduction","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Vinegar","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Whipped, Compound, and Emulsified Butter","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Wine","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Wine Reduction","0","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("*** Salsas ***","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Berry Kiwi Salsa \n 9Pineapple, Mango, Red Onion, Garlic, Lime Juice, Sugar, Salt, Pepper","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Creole Salsa \n 9Tomato Salsa, Celery, Onion, Green Pepper, Cilantro Hot Sauce","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cucumber Salsa","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Green Chile Salsa","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mango Salsa","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Onion Salsa","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pineapple Salsa \n 9Pineapple, Mango, Red Onion, Garlic, Lime Juice, Sugar, Salt, Pepper","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomatillo Salsa","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomato Salsa","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tropical Fruit Salsa \n 9Guava, Mango, Papaya, Passion, Red Pepper, Scallions, Olive Oil, Cilantro, Lime Juice, Crushed Red Pepper, Black Pepper, Salt","0","0","0","",R.drawable.mic_done_black_24dp));
                break;
            // button btnx45 "Vegetables Fruits
            case "btnx45":
                data.add(new CopListdata("*** Vegetables ***","","","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Artichoke","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Asparagus","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Avocados","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Bean Sprouts","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Beans-Edible","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Beans-Inedible","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Beet","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Bell Pepper, Red","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Breadfruit","1","120","0","29",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Broccoli","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Brussel Sprouts","3","40","0","7",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cabbage","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Carrot","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Cauliflower","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Celeriac/Celery Root","2","48","0","10",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Celery Green, Giant Pascal","2","16","0","4",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chard Swiss, Multicolored","2","24","0","4",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Chili Peppers Fresh And Dry \n 9Listed In Order of Scoville Units","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Collard Greens","2","28","0","5",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Corn","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Cucumber","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Dandelion","3","48","1","8",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dried Beans/Peas/Lentils/Flageolet","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Edamame","9","124","0","23",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Eggplant","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Escarole","2","24","0","4",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Fennel","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Garlic","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Kale","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Kohlrabi","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Leafy Greens","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Leek/Baby Leek","1","64","0","14",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Legume and Seed Shoots","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Lettuce","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Lotus Root","0","18","0","4",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Microgreens","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Mushrooms","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("New Mexican 6-4 Heritage","","1786","","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Okra Red/Green","2","36","0","8",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Onion","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Oyster Plant","0","18","0","4",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Parsnip","0","18","0","4",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Peas-Edible","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Peas-Inedible","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Radicchio","0","6","0","2",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Radishes","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Roots and Tubers","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Salsify Black/White","0","18","0","4",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Sea Vegetables","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Shallot","1","64","0","14",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Shoots and Stems","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Sorrel","2","24","0","4",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Spinach","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Summer Squash","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Sweet Potatoes","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Tomatillo","0","44","0","8",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tomato","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Truffles","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Turnip","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Water Chestnut","0","18","0","4",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Winter Squash","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));

                data.add(new CopListdata("*** Fruits ***","0","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Apples","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Apricots","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Banana","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Berries","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Cherimoya","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Cherries","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Currants","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Dates","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Dragon Fruit","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Feijoa","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Figs","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Grapefruit","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Grapes","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Guava","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Kiwi","","0","0","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Kumquat","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Lemons","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Limes","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Lychee","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Mango","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Mangostene","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Medlar","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Melons","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Minneola","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Murcott","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Nectarines","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Olives","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Oranges","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Papayas","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Passion Fruit","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Peaches","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Pears","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Persimmon","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Physallis/Cape Gooseberry","1","52","0","12",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pineapple","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Plums","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Pomegranate","1","108","0","25",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Pomelo","","0","0","",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Prickly Pear","","0","0","0",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Quince","0","64","0","14",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Rhubarb","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                data.add(new CopListdata("Sapodilla/Mexican Pear","1","64","0","16",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Star Fruit/Carambola","1","41","0","9",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tamarillo/New Zealand","3","42","1","5",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Tangerine/Mandarin","1","48","0","11",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Ugly/Spanish Citrus","1","40","0","9",R.drawable.mic_done_black_24dp));
                data.add(new CopListdata("Watermelon","","","","",R.drawable.ic_keyboard_arrow_right_black_24dp));
                break;
        }
        return data;
    }




}